measurements = [
      "#",
      "bag",
      "bunch",
      "can",
      "clove",
      "cube",
      "dash",
      "envelope",
      "gram",
      "head",
      "inch",
      "kilogram",
      "lb",
      "ounce",
      "oz",
      "package",
      "packet",
      "piece",
      "pinch",
      "pound",
      "sheet",
      "slice",
      "strip",
      "Tbsp",
      "bottle",
      "c",
      "cup",
      "dessertspoon",
      "fl oz",
      "fluid ounce",
      "fluid oz",
      "gal",
      "gallon",
      "jar",
      "liter",
      "milliliter",
      "ml",
      "pint",
      "pt",
      "qt",
      "quart",
      "tablespoon",
      "teaspoon",
      "tsp",
    ]